version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/wan
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./backend/outputs:/app/backend/outputs
      - ./models:/app/models
  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python backend/worker.py
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/wan
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    volumes:
      - ./config:/app/config
      - ./backend/outputs:/app/backend/outputs
      - ./models:/app/models
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
volumes:
  postgres-data:
  minio-data:
