# WAN2.2 Model Manifest - Minimal Working Version
schema_version = 1

# Text-to-Video A14B Model
[models."t2v-A14B@2.2.0"]
description = "WAN2.2 Text-to-Video A14B Model"
version = "2.2.0"
variants = ["fp16"]
default_variant = "fp16"
allow_patterns = ["*"]
required_components = []

[[models."t2v-A14B@2.2.0".files]]
path = "configuration.json"
size = 47
sha256 = "0000000000000000000000000000000000000000000000000000000000000000"
component = "config"

[models."t2v-A14B@2.2.0".sources]
priority = ["local://wan22/t2v-A14B@2.2.0"]

# Image-to-Video A14B Model
[models."i2v-A14B@2.2.0"]
description = "WAN2.2 Image-to-Video A14B Model"
version = "2.2.0"
variants = ["fp16"]
default_variant = "fp16"
allow_patterns = ["*"]
required_components = []

[[models."i2v-A14B@2.2.0".files]]
path = "configuration.json"
size = 47
sha256 = "0000000000000000000000000000000000000000000000000000000000000000"
component = "config"

[models."i2v-A14B@2.2.0".sources]
priority = ["local://wan22/i2v-A14B@2.2.0"]

# Text+Image-to-Video 5B Model
[models."ti2v-5b@2.2.0"]
description = "WAN2.2 Text+Image-to-Video 5B Model"
version = "2.2.0"
variants = ["fp16"]
default_variant = "fp16"
allow_patterns = ["*"]
required_components = []

[[models."ti2v-5b@2.2.0".files]]
path = "configuration.json"
size = 47
sha256 = "0000000000000000000000000000000000000000000000000000000000000000"
component = "config"

[models."ti2v-5b@2.2.0".sources]
priority = ["local://wan22/ti2v-5b@2.2.0"]