name: Documentation Build

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "backend/**/*.py"
      - "frontend/src/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "backend/**/*.py"
      - "frontend/src/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Fix for Git error - ensure we have full history and proper token access
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
          pip install markdown beautifulsoup4 requests pytest pyyaml

      - name: Install Node.js dependencies
        continue-on-error: true
        run: |
          cd frontend
          npm ci --prefer-offline --no-audit

      - name: Generate API documentation
        continue-on-error: true
        run: |
          python -m tools.doc_generator.cli generate --generate-api

      - name: Validate documentation links
        continue-on-error: true
        run: |
          python -m tools.doc_generator.cli validate --links-only || echo "Link validation completed with warnings"

      - name: Build documentation
        run: |
          mkdocs build

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  validate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown beautifulsoup4 requests

      - name: Check documentation completeness
        continue-on-error: true
        run: |
          python -m tools.doc_generator.cli metadata scan || echo "Metadata scan completed with warnings"

      - name: Validate markdown syntax
        continue-on-error: true
        run: |
          python -m tools.doc_generator.cli validate --docs-dir=docs/ || echo "Markdown validation completed with warnings"

      - name: Check for broken internal links
        continue-on-error: true
        run: |
          python -m tools.doc_generator.cli validate --links-only || echo "Link validation completed with warnings"

      - name: Generate documentation metrics
        continue-on-error: true
        run: |
          python -m tools.doc_generator.cli validate --output=docs-metrics.json --format=json || echo "Metrics generation completed with warnings"
          # Ensure the file exists even if the command fails
          if [ ! -f docs-metrics.json ]; then
            echo '{"validation_passed": false, "error": "Validation failed"}' > docs-metrics.json
          fi

      - name: Upload documentation metrics
        uses: actions/upload-artifact@v4
        with:
          name: docs-metrics
          path: docs-metrics.json