name: Documentation Build

on:
  push:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "backend/**/*.py"
      - "frontend/src/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "docs/**"
      - "backend/**/*.py"
      - "frontend/src/**"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
          pip install -r backend/requirements.txt

      - name: Install Node.js dependencies
        run: |
          cd frontend
          npm ci

      - name: Generate API documentation
        run: |
          python tools/doc-generator/generate_api_docs.py

      - name: Validate documentation links
        run: |
          python tools/doc-generator/validate_links.py --check-external=false

      - name: Build documentation
        run: |
          mkdocs build --strict

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: site/

      - name: Deploy to GitHub Pages (main branch only)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  validate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown beautifulsoup4 requests

      - name: Check documentation completeness
        run: |
          python tools/doc-generator/check_completeness.py

      - name: Validate markdown syntax
        run: |
          python tools/doc-generator/validate_markdown.py docs/

      - name: Check for broken internal links
        run: |
          python tools/doc-generator/validate_links.py --internal-only

      - name: Generate documentation metrics
        run: |
          python tools/doc-generator/generate_metrics.py --output=docs-metrics.json

      - name: Upload documentation metrics
        uses: actions/upload-artifact@v4
        with:
          name: docs-metrics
          path: docs-metrics.json
